//! Shared types used across Fawx crates.
//!
//! Defines core data structures for user input, intents, action plans,
//! and agent responses.

use serde::{Deserialize, Serialize};
use std::collections::HashMap;

/// Context available to skills during execution.
///
/// Provides metadata about the current invocation: which channel triggered it,
/// which node is running it, who sent the request, and the API version.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ExecutionContext {
    /// Which channel this request came from
    pub channel_id: Option<String>,
    /// Node identifier (for multi-node setups)
    pub node_id: Option<String>,
    /// User/sender identifier (channel-specific)
    pub user_id: Option<String>,
    /// Timestamp of the request (ms since epoch)
    pub timestamp_ms: u64,
    /// API version the skill was compiled against
    pub api_version: String,
}

/// A base64-encoded image attachment for multimodal messages.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ImageAttachment {
    /// MIME type (e.g., "image/jpeg").
    pub media_type: String,
    /// Base64-encoded image data.
    pub data: String,
}

/// A base64-encoded document attachment for multimodal messages.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct DocumentAttachment {
    /// MIME type (e.g., "application/pdf").
    pub media_type: String,
    /// Base64-encoded document data.
    pub data: String,
    /// Original filename when available.
    pub filename: Option<String>,
}

/// User input received from voice, text, or other sources.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UserInput {
    /// The raw input text
    pub text: String,

    /// Input source (voice, text, notification, etc.)
    pub source: InputSource,

    /// Unix timestamp in milliseconds since epoch
    pub timestamp: u64,

    /// Optional context from previous conversation
    pub context_id: Option<String>,

    /// Base64-encoded images attached to the input.
    #[serde(default)]
    pub images: Vec<ImageAttachment>,

    /// Base64-encoded documents attached to the input.
    #[serde(default)]
    pub documents: Vec<DocumentAttachment>,
}

/// Source of user input.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq, Hash)]
pub enum InputSource {
    /// Voice command
    Voice,
    /// Text input (CLI, overlay, etc.)
    Text,
    /// Triggered by notification
    Notification,
    /// Scheduled/proactive action
    Scheduled,
    /// Message from an external channel (id identifies which).
    Channel(String),
    /// Message from HTTP API.
    Http,
}

/// Classified intent from user input.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Intent {
    /// Intent category
    pub category: IntentCategory,

    /// Classification confidence (0.0 - 1.0)
    pub confidence: f32,

    /// Extracted entities (e.g., app name, contact, time)
    pub entities: HashMap<String, String>,

    /// Original user input
    pub raw_input: String,
}

/// Categories of user intents.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub enum IntentCategory {
    /// Launch an application
    LaunchApp,
    /// Search for information
    Search,
    /// Navigate to a location
    Navigate,
    /// Send a message
    Message,
    /// Calendar/scheduling action
    Calendar,
    /// Modify device settings
    Settings,
    /// Answer a question
    Question,
    /// Complex multi-step task
    ComplexTask,
    /// Conversational (no clear action)
    Conversation,
}

/// Action plan generated by the agent.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionPlan {
    /// Plan ID for tracking
    pub id: String,

    /// List of steps to execute
    pub steps: Vec<ActionStep>,

    /// Human-readable plan description
    pub description: String,

    /// Whether user confirmation is required
    pub requires_confirmation: bool,
}

/// Individual step in an action plan.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionStep {
    /// Step ID
    pub id: String,

    /// Action to perform (tap, swipe, launch_app, etc.)
    pub action: String,

    /// Target of the action (element name, app name, etc.)
    pub target: String,

    /// Additional parameters for the action
    pub parameters: HashMap<String, String>,

    /// Whether this step requires confirmation
    pub confirmation_required: bool,
}

/// Result of executing an action.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ActionResult {
    /// Action step ID that was executed
    pub step_id: String,

    /// Whether the action succeeded
    pub success: bool,

    /// Result message or error description
    pub message: String,

    /// Optional data returned by the action
    pub data: Option<HashMap<String, String>>,
}

/// Agent response to user input.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct AgentResponse {
    /// Response text (for voice/display)
    pub text: String,

    /// Actions that were taken (if any)
    pub actions_taken: Vec<ActionResult>,

    /// Whether the response is complete or waiting for more input
    pub complete: bool,

    /// Suggested follow-up actions
    pub suggestions: Vec<String>,
}

/// Phone actions trait - abstraction for phone control.
///
/// This trait is implemented by both the simulator (pre-PoC) and
/// real phone control (PoC/OS).
pub trait PhoneActions {
    /// Tap on a named UI element or coordinates.
    fn tap(&mut self, target: &str) -> crate::error::Result<ActionResult>;

    /// Swipe in a direction.
    fn swipe(&mut self, direction: SwipeDirection) -> crate::error::Result<ActionResult>;

    /// Type text into the focused field.
    fn type_text(&mut self, text: &str) -> crate::error::Result<ActionResult>;

    /// Launch an application by name or package ID.
    fn launch_app(&mut self, name: &str) -> crate::error::Result<ActionResult>;

    /// Go to home screen.
    fn go_home(&mut self) -> crate::error::Result<ActionResult>;

    /// Go back (back button).
    fn go_back(&mut self) -> crate::error::Result<ActionResult>;

    /// Read current screen state.
    fn read_screen(&self) -> crate::error::Result<ScreenState>;

    /// Get current notifications.
    fn get_notifications(&self) -> crate::error::Result<Vec<Notification>>;

    /// Set a system setting.
    fn set_setting(&mut self, key: &str, value: &str) -> crate::error::Result<ActionResult>;
}

/// Swipe direction for gestures.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub enum SwipeDirection {
    Up,
    Down,
    Left,
    Right,
}

/// Current screen state (from UI tree or screenshot).
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct ScreenState {
    /// Current app/activity name
    pub current_app: String,

    /// Visible UI elements
    pub elements: Vec<UiElement>,

    /// Raw text content visible on screen
    pub text_content: String,
}

/// A UI element on the screen.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct UiElement {
    /// Element ID or name
    pub id: String,

    /// Element type (button, text_field, etc.)
    pub element_type: String,

    /// Visible text
    pub text: String,

    /// Whether the element is clickable
    pub clickable: bool,
}

/// A notification from the system.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct Notification {
    /// Notification ID
    pub id: String,

    /// Source app package
    pub app: String,

    /// Notification title
    pub title: String,

    /// Notification content
    pub content: String,

    /// Unix timestamp in milliseconds since epoch
    pub timestamp: u64,
}

#[cfg(test)]
mod tests {
    use super::{InputSource, UserInput};

    #[test]
    fn user_input_default_images_empty() {
        let input: UserInput = serde_json::from_value(serde_json::json!({
            "text": "hello",
            "source": "Text",
            "timestamp": 123,
            "context_id": null
        }))
        .expect("deserialize user input");

        assert_eq!(input.text, "hello");
        assert_eq!(input.source, InputSource::Text);
        assert!(input.images.is_empty());
    }
}
