package ai.citros.chat

import android.content.Context
import android.content.SharedPreferences
import android.os.Looper
import android.util.Log
import ai.citros.core.PrivacyList
import org.json.JSONArray
import org.json.JSONObject
import java.util.WeakHashMap

/**
 * Production privacy list backed by shared preferences.
 *
 * Writes are synchronous (`commit`) for durability. Callers should avoid invoking
 * [add] / [remove] from the main thread to prevent UI jank.
 */
class SharedPrefsPrivacyList internal constructor(
    private val prefs: SharedPreferences,
    private val isMainThread: () -> Boolean,
    private val isDebugBuild: () -> Boolean
) : PrivacyList {
    private val prefsLock: Any = lockForPrefs(prefs)

    constructor(context: Context) : this(
        prefs = context.getSharedPreferences(CITROS_PREFS, Context.MODE_PRIVATE),
        isMainThread = { Looper.getMainLooper().thread == Thread.currentThread() },
        isDebugBuild = { BuildConfig.DEBUG }
    )


    override fun isPrivate(packageName: String): Boolean {
        val normalized = packageName.trim()
        if (normalized.isEmpty()) return false
        return synchronized(prefsLock) {
            val current = prefs.getStringSet(KEY_PRIVACY_APP_LIST, emptySet()) ?: emptySet()
            current.contains(normalized)
        }
    }

    override fun getAll(): Set<String> = synchronized(prefsLock) {
        // Return an immutable snapshot to avoid callers mutating the SharedPreferences-backed set.
        prefs.getStringSet(KEY_PRIVACY_APP_LIST, emptySet())?.toSet() ?: emptySet()
    }

    override fun add(packageName: String) {
        val normalized = packageName.trim()
        if (normalized.isEmpty()) return
        warnIfMainThread("add")
        synchronized(prefsLock) {
            val updated = prefs.getStringSet(KEY_PRIVACY_APP_LIST, emptySet())
                ?.toMutableSet()
                ?: mutableSetOf()
            updated.add(normalized)
            val committed = prefs.edit().putStringSet(KEY_PRIVACY_APP_LIST, updated).commit()
            if (!committed) {
                Log.e(TAG, "add: failed to persist privacy list update (package_redacted=true)")
                throw IllegalStateException("Failed to persist privacy list update")
            }
        }
    }

    override fun remove(packageName: String) {
        val normalized = packageName.trim()
        if (normalized.isEmpty()) return
        warnIfMainThread("remove")
        synchronized(prefsLock) {
            val updated = prefs.getStringSet(KEY_PRIVACY_APP_LIST, emptySet())
                ?.toMutableSet()
                ?: mutableSetOf()
            updated.remove(normalized)
            val committed = prefs.edit().putStringSet(KEY_PRIVACY_APP_LIST, updated).commit()
            if (!committed) {
                Log.e(TAG, "remove: failed to persist privacy list update (package_redacted=true)")
                throw IllegalStateException("Failed to persist privacy list update")
            }
        }
    }

    /**
     * Seeds privacy defaults on first run.
     *
     * Returns true when defaults were applied.
     */
    fun seedDefaultsIfNeeded(): Boolean = synchronized(prefsLock) {
        if (prefs.contains(KEY_PRIVACY_APP_LIST)) return@synchronized false

        val committed = prefs.edit()
            .putStringSet(KEY_PRIVACY_APP_LIST, DEFAULT_PRIVACY_PACKAGES)
            .putBoolean(KEY_PRIVACY_RECOVERY_PROMPT_PENDING, true)
            .commit()
        if (!committed) {
            Log.e(TAG, "seedDefaultsIfNeeded: failed to persist defaults")
            throw IllegalStateException("Failed to seed default privacy list")
        }
        true
    }

    fun exportToJson(): String = synchronized(prefsLock) {
        val packages = prefs.getStringSet(KEY_PRIVACY_APP_LIST, emptySet())
            ?.toList()
            ?.sorted()
            ?: emptyList()
        val payload = JSONObject()
            .put("version", BACKUP_FORMAT_VERSION)
            .put("privacyPackages", JSONArray(packages))
        payload.toString()
    }

    /**
     * Restores privacy list from a JSON payload generated by [exportToJson].
     * Returns the number of imported package names.
     */
    fun restoreFromJson(json: String): Int = synchronized(prefsLock) {
        val parsed = JSONObject(json)
        val version = parsed.optInt("version", -1)
        if (version != BACKUP_FORMAT_VERSION) {
            throw IllegalArgumentException("Unsupported backup format version: $version")
        }

        val packagesArray = parsed.optJSONArray("privacyPackages")
            ?: throw IllegalArgumentException("Missing privacyPackages")

        val restored = linkedSetOf<String>()
        for (index in 0 until packagesArray.length()) {
            val pkg = packagesArray.optString(index, "").trim()
            if (pkg.isNotEmpty()) {
                restored.add(pkg)
            }
        }
        if (restored.isEmpty()) {
            throw IllegalArgumentException("Backup must include at least one privacy package")
        }

        val committed = prefs.edit()
            .putStringSet(KEY_PRIVACY_APP_LIST, restored)
            .putBoolean(KEY_PRIVACY_RECOVERY_PROMPT_PENDING, false)
            .commit()
        if (!committed) {
            Log.e(TAG, "restoreFromJson: failed to persist imported list")
            throw IllegalStateException("Failed to restore privacy list")
        }
        restored.size
    }

    fun isRecoveryPromptPending(): Boolean = synchronized(prefsLock) {
        prefs.getBoolean(KEY_PRIVACY_RECOVERY_PROMPT_PENDING, false)
    }

    fun markRecoveryPromptHandled() = synchronized(prefsLock) {
        val committed = prefs.edit().putBoolean(KEY_PRIVACY_RECOVERY_PROMPT_PENDING, false).commit()
        if (!committed) {
            Log.e(TAG, "markRecoveryPromptHandled: failed to persist recovery prompt state")
            throw IllegalStateException("Failed to persist recovery prompt state")
        }
    }

    private fun warnIfMainThread(operation: String) {
        if (isMainThread()) {
            val message = "$operation: called on main thread; synchronous commit may cause jank"
            if (isDebugBuild()) {
                throw IllegalStateException(message)
            }
            Log.w(TAG, message)
        }
    }

    companion object {
        const val KEY_PRIVACY_APP_LIST = "privacy_app_list"
        const val KEY_PRIVACY_RECOVERY_PROMPT_PENDING = "privacy_recovery_prompt_pending"
        private const val TAG = "CitrosPrivacyList"
        private val lockRegistry = WeakHashMap<SharedPreferences, Any>()

        private const val BACKUP_FORMAT_VERSION = 1

        internal val DEFAULT_PRIVACY_PACKAGES = setOf(
            // Banking & payments
            "com.revolut.revolut",
            "com.paypal.android.p2pmobile",
            "com.coinbase.android",
            // Health
            "com.google.android.apps.fitness",
            "com.fitbit.FitbitMobile",
            "com.myfitnesspal.android",
            // Messaging
            "com.whatsapp",
            "org.telegram.messenger",
            "com.facebook.orca",
            "org.thoughtcrime.securesms",
            "com.google.android.apps.messaging"
        )

        private fun lockForPrefs(prefs: SharedPreferences): Any = synchronized(lockRegistry) {
            lockRegistry.getOrPut(prefs) { Any() }
        }
    }
}
