package ai.citros.core

import android.util.Log

/**
 * Guards against unverified side-effect completion claims in final assistant text.
 *
 * The guard tracks lightweight execution artifacts from successful tool calls and,
 * before final text is emitted, rewrites side-effect success claims when no
 * matching execution evidence exists.
 */
internal class SideEffectCompletionGuard(
    private val onGuardTriggered: ((GuardFireTelemetry) -> Unit)? = null
) {

    internal data class GuardFireTelemetry(
        val missingClaims: Set<String>,
        val evidencedClaims: Set<String>,
        val recordedArtifactCount: Int,
        val uiMutatingArtifactCount: Int,
        val preservedContextIncluded: Boolean,
        val originalTextPreview: String
    )

    private enum class ClaimType(val label: String) {
        EMAIL_SEND("email sending"),
        BOOKING("booking"),
        SCHEDULING("scheduling")
    }

    private data class ExecutionArtifact(
        val toolName: String,
        val succeeded: Boolean,
        val inputSummary: String,
        val resultSummary: String,
        val targetLabel: String?,
        val fromApp: String?,
        val toApp: String?,
        val isUiMutatingTool: Boolean
    )

    private val artifacts = mutableListOf<ExecutionArtifact>()
    private val evidencedClaims = mutableSetOf<ClaimType>()

    /**
     * Records one tool execution for later claim-evidence correlation.
     *
     * @param toolCall Tool invocation requested by the model.
     * @param actionResult Result emitted by the tool execution.
     * @param screenBefore Screen snapshot captured before the tool ran.
     * @param screenAfter Screen snapshot captured after the tool ran.
     * @param isUiMutatingTool Whether this tool is classified as UI-mutating by the executor.
     */
    fun recordExecution(
        toolCall: ToolCall,
        actionResult: ToolResult,
        screenBefore: ScreenContent?,
        screenAfter: ScreenContent?,
        isUiMutatingTool: Boolean
    ) {
        val artifact = ExecutionArtifact(
            toolName = toolCall.name,
            succeeded = !actionResult.isError,
            inputSummary = flattenToText(toolCall.input),
            resultSummary = actionResult.text,
            targetLabel = extractTargetLabel(toolCall, screenBefore),
            fromApp = screenBefore?.packageName,
            toApp = screenAfter?.packageName,
            isUiMutatingTool = isUiMutatingTool
        )
        artifacts += artifact

        if (!artifact.succeeded) return
        evidencedClaims += classifyEvidence(artifact)
    }

    /**
     * Rewrites side-effect completion claims that cannot be backed by execution evidence.
     *
     * @param finalText Final assistant message generated by the loop.
     * @return Original text when evidence is sufficient (or no claims were detected),
     *   otherwise a `NOT_COMPLETED` rewrite that blocks false success claims.
     */
    fun guardFinalText(finalText: String?): String? {
        if (finalText.isNullOrBlank()) return finalText
        val claims = detectClaims(finalText)
        if (claims.isEmpty()) return finalText

        val missingEvidence = claims.filterNot { it in evidencedClaims }.toSet()
        if (missingEvidence.isEmpty()) return finalText

        val safeDiagnosticContext = extractSafeDiagnosticContext(finalText, missingEvidence)
        emitGuardTelemetry(finalText, missingEvidence, safeDiagnosticContext)
        return buildNotCompletedMessage(missingEvidence, safeDiagnosticContext)
    }

    private fun detectClaims(text: String): Set<ClaimType> {
        if (text.isBlank()) return emptySet()
        return splitIntoSentences(text)
            .flatMapTo(mutableSetOf()) { sentence -> detectClaimsInSentence(sentence) }
    }

    private fun detectClaimsInSentence(sentence: String): Set<ClaimType> {
        val claims = mutableSetOf<ClaimType>()
        if (hasAffirmativeClaim(sentence, EMAIL_CLAIM_PATTERNS)) {
            claims += ClaimType.EMAIL_SEND
        }
        if (hasAffirmativeClaim(sentence, BOOKING_CLAIM_PATTERNS)) {
            claims += ClaimType.BOOKING
        }
        if (hasAffirmativeClaim(sentence, SCHEDULING_CLAIM_PATTERNS)) {
            claims += ClaimType.SCHEDULING
        }
        return claims
    }

    private fun hasAffirmativeClaim(sentence: String, patterns: List<Regex>): Boolean {
        if (sentence.isBlank()) return false
        val normalizedSentence = sentence.lowercase()

        for (pattern in patterns) {
            for (match in pattern.findAll(normalizedSentence)) {
                val window = negationWindow(normalizedSentence, match.range)
                if (!NEGATION_CUE_REGEX.containsMatchIn(window)) {
                    return true
                }
            }
        }
        return false
    }

    private fun negationWindow(text: String, matchRange: IntRange): String {
        val start = (matchRange.first - NEGATION_WINDOW_CHARS).coerceAtLeast(0)
        val endExclusive = (matchRange.last + 1 + NEGATION_WINDOW_CHARS).coerceAtMost(text.length)
        return text.substring(start, endExclusive)
    }

    private fun splitIntoSentences(text: String): List<String> {
        return SENTENCE_SPLIT_REGEX
            .split(text)
            .map { it.trim() }
            .filter { it.isNotBlank() }
    }

    private fun classifyEvidence(artifact: ExecutionArtifact): Set<ClaimType> {
        if (!artifact.isUiMutatingTool) return emptySet()

        val claims = mutableSetOf<ClaimType>()

        val targetTokens = tokenize(artifact.targetLabel)
        val resultTokens = tokenize(artifact.resultSummary)
        val actionTokens = buildSet {
            addAll(tokenize(artifact.toolName))
            addAll(tokenize(artifact.inputSummary))
            addAll(targetTokens)
        }
        val contextTokens = buildSet {
            addAll(actionTokens)
            addAll(resultTokens)
            addAll(tokenize(artifact.fromApp))
            addAll(tokenize(artifact.toApp))
        }

        val emailTargeted = targetTokens.any { it in EMAIL_TARGET_TOKENS }
        val emailCompletionInResult = resultTokens.any { it in EMAIL_COMPLETION_TOKENS }
        val emailActionObserved = actionTokens.any { it in EMAIL_ACTION_TOKENS }
        val emailContextObserved =
            contextTokens.any { it in EMAIL_CONTEXT_TOKENS } ||
                isKnownEmailPackage(artifact.fromApp) ||
                isKnownEmailPackage(artifact.toApp)
        if (emailTargeted || (emailCompletionInResult && emailContextObserved && emailActionObserved)) {
            claims += ClaimType.EMAIL_SEND
        }

        val bookingTargeted = targetTokens.any { it in BOOKING_TARGET_TOKENS }
        val bookingCompletionInResult = resultTokens.any { it in BOOKING_COMPLETION_TOKENS }
        val bookingActionObserved = actionTokens.any { it in BOOKING_ACTION_TOKENS }
        val bookingContextObserved = contextTokens.any { it in BOOKING_CONTEXT_TOKENS }
        if (bookingTargeted || (bookingCompletionInResult && bookingContextObserved && bookingActionObserved)) {
            claims += ClaimType.BOOKING
        }

        val schedulingTargeted = targetTokens.any { it in SCHEDULING_TARGET_TOKENS }
        val schedulingCompletionInResult = resultTokens.any { it in SCHEDULING_COMPLETION_TOKENS }
        val schedulingActionObserved = actionTokens.any { it in SCHEDULING_ACTION_TOKENS }
        val schedulingContextObserved = contextTokens.any { it in SCHEDULING_CONTEXT_TOKENS }
        if (schedulingTargeted || (schedulingCompletionInResult && schedulingContextObserved && schedulingActionObserved)) {
            claims += ClaimType.SCHEDULING
        }

        return claims
    }

    private fun buildNotCompletedMessage(
        missingEvidence: Set<ClaimType>,
        safeDiagnosticContext: String?
    ): String {
        val labels = missingEvidence
            .toList()
            .sortedBy { it.ordinal }
            .joinToString(", ") { it.label }

        val contextClause = safeDiagnosticContext?.let { " Context preserved: $it" } ?: ""
        return "NOT_COMPLETED: I can't verify $labels from this run's execution evidence.$contextClause " +
            "Next action required: continue and explicitly perform/verify that step before claiming success."
    }

    private fun extractSafeDiagnosticContext(
        finalText: String,
        missingEvidence: Set<ClaimType>
    ): String? {
        val safeSentences = splitIntoSentences(finalText)
            .map { normalizeWhitespace(it) }
            .filter { sentence ->
                val sentenceClaims = detectClaimsInSentence(sentence)
                sentenceClaims.none { it in missingEvidence }
            }
            .filter { it.isNotBlank() }

        if (safeSentences.isEmpty()) return null
        return safeSentences
            .joinToString(" ")
            .take(MAX_PRESERVED_CONTEXT_CHARS)
            .ifBlank { null }
    }

    private fun emitGuardTelemetry(
        originalText: String,
        missingEvidence: Set<ClaimType>,
        safeDiagnosticContext: String?
    ) {
        val telemetry = GuardFireTelemetry(
            missingClaims = missingEvidence
                .toList()
                .sortedBy { it.ordinal }
                .mapTo(linkedSetOf()) { it.name },
            evidencedClaims = evidencedClaims
                .toList()
                .sortedBy { it.ordinal }
                .mapTo(linkedSetOf()) { it.name },
            recordedArtifactCount = artifacts.size,
            uiMutatingArtifactCount = artifacts.count { it.isUiMutatingTool },
            preservedContextIncluded = safeDiagnosticContext != null,
            originalTextPreview = normalizeWhitespace(originalText).take(ORIGINAL_TEXT_PREVIEW_MAX_CHARS)
        )

        onGuardTriggered?.invoke(telemetry)
        Log.w(
            TAG,
            "Guard rewrote side-effect completion claim(s): " +
                "missing=${telemetry.missingClaims.joinToString(",")} " +
                "evidenced=${telemetry.evidencedClaims.joinToString(",")} " +
                "artifacts=${telemetry.recordedArtifactCount} " +
                "uiMutatingArtifacts=${telemetry.uiMutatingArtifactCount} " +
                "preservedContext=${telemetry.preservedContextIncluded} " +
                "originalPreview=\"${telemetry.originalTextPreview}\""
        )
    }

    private fun extractTargetLabel(toolCall: ToolCall, screenBefore: ScreenContent?): String? {
        return when (toolCall.name) {
            "tap_text" -> toolCall.input["text"] as? String
            "tap", "long_press" -> {
                val elementId = (toolCall.input["element_id"] as? Number)?.toInt() ?: return null
                val element = screenBefore?.elements?.firstOrNull { it.id == elementId } ?: return null
                listOfNotNull(element.text, element.contentDescription, element.className)
                    .joinToString(" ")
                    .ifBlank { null }
            }
            else -> null
        }
    }

    private fun flattenToText(value: Any?): String {
        val parts = mutableListOf<String>()
        fun visit(node: Any?) {
            when (node) {
                null -> Unit
                is String -> parts += node
                is Number, is Boolean -> parts += node.toString()
                is Map<*, *> -> node.values.forEach { visit(it) }
                is Iterable<*> -> node.forEach { visit(it) }
                is Array<*> -> node.forEach { visit(it) }
                else -> parts += node.toString()
            }
        }
        visit(value)
        return parts.joinToString(" ")
    }

    private fun tokenize(text: String?): Set<String> {
        if (text.isNullOrBlank()) return emptySet()
        return TOKEN_REGEX.findAll(text.lowercase())
            .map { it.value }
            .toSet()
    }

    private fun normalizeWhitespace(text: String): String = text.replace(WHITESPACE_REGEX, " ").trim()

    private fun isKnownEmailPackage(packageName: String?): Boolean {
        if (packageName.isNullOrBlank()) return false
        val normalized = packageName.trim().lowercase()

        if (normalized in KNOWN_EMAIL_PACKAGES) return true
        if (KNOWN_EMAIL_PACKAGE_PREFIXES.any { prefix ->
                normalized == prefix || normalized.startsWith("$prefix.")
            }
        ) {
            return true
        }

        val segments = normalized
            .split('.')
            .filter { it.isNotBlank() }

        return segments.any { it in EMAIL_PACKAGE_FALLBACK_SEGMENTS }
    }

    private companion object {
        private const val TAG = "SideEffectGuard"
        private const val ORIGINAL_TEXT_PREVIEW_MAX_CHARS = 280
        private const val MAX_PRESERVED_CONTEXT_CHARS = 220
        private const val NEGATION_WINDOW_CHARS = 24

        private val TOKEN_REGEX = Regex("[a-z0-9]+")
        private val WHITESPACE_REGEX = Regex("\\s+")
        private val SENTENCE_SPLIT_REGEX = Regex("(?<=[.!?])\\s+|\\n+")
        private val NEGATION_CUE_REGEX = Regex(
            "\\b(?:not|never|did\\s*not|didn['’]t|haven['’]t|have\\s*not|wasn['’]t|was\\s*not|weren['’]t|were\\s*not|can['’]t|cannot|couldn['’]t|failed|failure|unable|unsent|pending|draft)\\b",
            RegexOption.IGNORE_CASE
        )

        private val EMAIL_CLAIM_PATTERNS = listOf(
            Regex("\\b(?:i|we)\\s+(?:have\\s+|just\\s+|successfully\\s+)?(?:sent|delivered)\\b[^.!?]{0,40}\\b(?:email|message)\\b", RegexOption.IGNORE_CASE),
            Regex("\\b(?:your|the)\\s+(?:email|message)\\s+(?:has\\s+been|is|was)\\s+(?:sent|delivered)\\b", RegexOption.IGNORE_CASE),
            Regex("\\b(?:email|message)\\s+(?:sent|delivered)\\b", RegexOption.IGNORE_CASE)
        )

        private val BOOKING_CLAIM_PATTERNS = listOf(
            Regex("\\b(?:i|we)\\s+(?:have\\s+|just\\s+|successfully\\s+)?(?:booked|reserved|confirmed)\\b[^.!?]{0,40}\\b(?:reservation|booking|flight|hotel|ticket|trip)\\b", RegexOption.IGNORE_CASE),
            Regex("\\b(?:your|the)\\s+(?:reservation|booking|flight|hotel|ticket|trip)\\s+(?:has\\s+been|is|was)\\s+(?:booked|reserved|confirmed)\\b", RegexOption.IGNORE_CASE),
            Regex("\\b(?:reservation|booking)\\s+(?:confirmed|booked|reserved)\\b", RegexOption.IGNORE_CASE)
        )

        private val SCHEDULING_CLAIM_PATTERNS = listOf(
            Regex("\\b(?:i|we)\\s+(?:have\\s+|just\\s+|successfully\\s+)?(?:scheduled|booked|created|set\\s+up)\\b[^.!?]{0,40}\\b(?:appointment|meeting|event|calendar(?:\\s+event)?)\\b", RegexOption.IGNORE_CASE),
            Regex("\\b(?:your|the)\\s+(?:appointment|meeting|event|calendar(?:\\s+event)?)\\s+(?:has\\s+been|is|was)\\s+(?:scheduled|booked|created|set\\s+up)\\b", RegexOption.IGNORE_CASE),
            Regex("\\b(?:appointment|meeting|event|calendar(?:\\s+event)?)\\s+(?:scheduled|booked|created)\\b", RegexOption.IGNORE_CASE)
        )

        private val EMAIL_TARGET_TOKENS = setOf("send", "sent", "submit", "submitted", "deliver", "delivered")
        private val EMAIL_ACTION_TOKENS = setOf(
            "send", "sent", "submit", "submitted", "deliver", "delivered", "compose", "reply", "forward", "queue", "queued"
        )
        private val EMAIL_COMPLETION_TOKENS = setOf("sent", "delivered", "submitted", "queued")
        private val EMAIL_CONTEXT_TOKENS = setOf(
            "email", "mail", "gmail", "outlook", "message", "compose", "recipient", "subject", "inbox", "outbox", "draft", "gm"
        )

        private val BOOKING_TARGET_TOKENS = setOf("book", "booking", "reserve", "reservation", "checkout", "buy", "purchase", "ticket")
        private val BOOKING_ACTION_TOKENS = setOf(
            "book", "booking", "reserve", "reservation", "checkout", "buy", "purchase", "ticket", "confirm", "confirmed"
        )
        private val BOOKING_COMPLETION_TOKENS = setOf("booked", "reserved", "confirmed", "purchased")
        private val BOOKING_CONTEXT_TOKENS = setOf(
            "book", "booking", "reservation", "reserve", "flight", "hotel", "ticket", "trip", "itinerary", "checkout", "purchase"
        )

        private val SCHEDULING_TARGET_TOKENS = setOf("schedule", "scheduled", "appointment", "meeting", "calendar", "event", "invite")
        private val SCHEDULING_ACTION_TOKENS = setOf(
            "schedule", "scheduled", "appointment", "meeting", "calendar", "event", "invite", "create", "set", "reminder"
        )
        private val SCHEDULING_COMPLETION_TOKENS = setOf("scheduled", "booked", "created", "confirmed")
        private val SCHEDULING_CONTEXT_TOKENS = setOf(
            "schedule", "scheduled", "appointment", "meeting", "calendar", "event", "invite", "reminder"
        )

        private val KNOWN_EMAIL_PACKAGES = setOf(
            "com.google.android.gm",
            "com.microsoft.office.outlook",
            "com.yahoo.mobile.client.android.mail",
            "com.samsung.android.email.provider",
            "com.android.email",
            "com.my.mail",
            "com.aqua.mail",
            "com.ninefolders.hd3",
            "ch.protonmail.android",
            "com.protonmail.android",
            "eu.faircode.email",
            "me.bluemail.mail",
            "com.readdle.spark"
        )

        private val KNOWN_EMAIL_PACKAGE_PREFIXES = setOf(
            "com.microsoft.office.outlook",
            "com.yahoo.mobile.client.android.mail",
            "ch.protonmail",
            "com.protonmail"
        )

        private val EMAIL_PACKAGE_FALLBACK_SEGMENTS = setOf(
            "gmail",
            "outlook",
            "protonmail",
            "yahoomail",
            "bluemail",
            "fairemail",
            "spark",
            "k9",
            "aquamail"
        )
    }
}
