package ai.citros.core

/**
 * Tool definition for function calling.
 * 
 * @param name Tool name (e.g., "tap", "type_text")
 * @param description Human-readable description of what the tool does
 * @param inputSchema JSON Schema object defining the tool's input parameters
 */
data class Tool(
    val name: String,
    val description: String,
    val inputSchema: Map<String, Any>
)

/**
 * A tool call requested by the model.
 * 
 * @param id Unique identifier for this tool call (used to match with tool results)
 * @param name Tool name to execute
 * @param input Input parameters for the tool (parsed from JSON)
 */
data class ToolCall(
    val id: String,
    val name: String,
    val input: Map<String, Any>
)

/**
 * Token usage data from an API response.
 *
 * Tracks input/output tokens and Anthropic-specific cache metrics.
 * Used for context window management, cost tracking, and compaction decisions.
 *
 * [totalTokens] sums [inputTokens] + [outputTokens] for context window limit checks.
 * Cache tokens are billing metadata — they indicate how input tokens were served
 * (from cache vs. fresh) but do not add to context consumption. Use all four
 * fields with appropriate pricing tiers for cost calculations.
 *
 * Note: streaming responses do not currently populate usage. Only non-streaming
 * chat, chatWithTools, and describeImage paths return token counts.
 *
 * @param inputTokens Tokens consumed by the input (prompt + messages)
 * @param outputTokens Tokens generated by the model
 * @param cacheReadTokens Anthropic: input tokens served from prompt cache (cheaper but still consume context)
 * @param cacheWriteTokens Anthropic: input tokens written to prompt cache for future reuse
 */
data class TokenUsage(
    val inputTokens: Int,
    val outputTokens: Int,
    val cacheReadTokens: Int = 0,
    val cacheWriteTokens: Int = 0
) {
    /** Total tokens across all categories. */
    val totalTokens: Int get() = inputTokens + outputTokens
}

/**
 * Response from chatWithTools including text and/or tool calls.
 * 
 * @param text Assistant's text response, if any
 * @param toolCalls List of tool calls the model wants to execute (empty if none)
 * @param stopReason Why the model stopped: "end_turn" (done), "tool_use" (wants to use tools), etc.
 * @param usage Token usage from this API call (null if not available or not parsed)
 */
data class ChatResponse(
    val text: String?,
    val toolCalls: List<ToolCall>,
    val stopReason: String?,
    val usage: TokenUsage? = null
)

/**
 * Typed wrapper for tool execution results.
 *
 * Provides a structured [isError] flag so callers (e.g., [OutputClassifier])
 * can detect errors without sniffing the result text format. This is necessary
 * because different tool categories use different error formats:
 * - UI tools: "Failed: tap: could not tap element 5" (string prefix)
 * - File tools: {"ok":false,"tool":"read_file","error":"Access denied"} (JSON)
 * - Memory tools: {"ok":false,"tool":"remember","error":"..."} (JSON)
 *
 * The [text] content format remains unchanged per tool category — this type
 * adds the typed flag alongside, not changing the content format.
 *
 * @param text The raw result text (same format as before: plain strings for UI tools, JSON for file/memory tools)
 * @param isError Whether the tool execution resulted in an error
 */
data class ToolResult(
    val text: String,
    val isError: Boolean = false,
    val severity: ErrorSeverity? = null
)
