use crate::detector::ImprovementCandidate;
use crate::error::ImprovementError;
use fx_llm::{CompletionProvider, CompletionRequest, Message, ToolCall, ToolDefinition};
use serde::{Deserialize, Serialize};
use std::fmt;
use std::path::{Path, PathBuf};

const PLAN_TOOL_NAME: &str = "generate_fix_plan";

const PLANNER_SYSTEM_PROMPT: &str = "\
You are a code improvement planner. Given an analysis finding with evidence, \
generate a concrete fix plan by calling the generate_fix_plan tool. \
Assess risk conservatively: Low for test/config/doc changes, Medium for \
behavioral changes with tests, High for architectural or kernel changes.";

/// Risk level for a proposed fix.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[serde(rename_all = "snake_case")]
pub enum RiskLevel {
    /// Safe: test-only, config, or documentation change.
    Low,
    /// Moderate: behavioral change with test coverage.
    Medium,
    /// High: architectural change, kernel modification, or untestable.
    High,
}

impl fmt::Display for RiskLevel {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        match self {
            Self::Low => write!(f, "low"),
            Self::Medium => write!(f, "medium"),
            Self::High => write!(f, "high"),
        }
    }
}

/// A single file change proposed by the planner.
#[derive(Debug, Clone, Serialize, Deserialize)]
pub struct FileChange {
    /// Path to the file being changed.
    pub path: PathBuf,
    /// Description of the change.
    pub description: String,
    /// Proposed new content (None if human must implement).
    pub content: Option<String>,
}

/// A concrete fix plan generated from an improvement candidate.
#[derive(Debug, Clone)]
pub struct FixPlan {
    /// The candidate this plan addresses.
    pub candidate: ImprovementCandidate,
    /// Target files to modify.
    pub target_files: Vec<PathBuf>,
    /// Natural language description of the fix.
    pub fix_description: String,
    /// Concrete code changes (None if human judgment required).
    pub code_changes: Option<Vec<FileChange>>,
    /// Risk assessment.
    pub risk: RiskLevel,
}

/// A candidate the planner could not turn into a fix plan.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct SkippedCandidate {
    /// Pattern name for the skipped candidate.
    pub name: String,
    /// Human-readable reason the candidate was skipped.
    pub reason: String,
}

pub fn skipped_candidate_summary(skipped_candidates: &[SkippedCandidate]) -> String {
    let count = skipped_candidates.len();
    let noun = if count == 1 {
        "candidate"
    } else {
        "candidates"
    };
    match shared_skip_reason(skipped_candidates) {
        Some(reason) => format!("{count} {noun} skipped ({reason})"),
        None => format!("{count} {noun} skipped (multiple planning errors)"),
    }
}

pub fn shared_skip_reason(skipped_candidates: &[SkippedCandidate]) -> Option<&str> {
    let first = skipped_candidates.first()?.reason.as_str();
    skipped_candidates
        .iter()
        .all(|candidate| candidate.reason == first)
        .then_some(first)
}

/// Result of planning a batch of improvement candidates.
#[derive(Debug, Clone)]
pub struct PlanningResult {
    /// Plans successfully produced by the LLM.
    pub plans: Vec<FixPlan>,
    /// Candidates skipped because planning failed for that candidate.
    pub skipped_candidates: Vec<SkippedCandidate>,
}

/// Final output of the improvement pipeline.
#[derive(Debug)]
pub struct ImprovementRunResult {
    /// Number of plans successfully generated by the planner.
    pub plans_generated: usize,
    /// Candidates skipped during planning, with reasons.
    pub skipped_candidates: Vec<SkippedCandidate>,
    /// Proposal files written to disk.
    pub proposals_written: Vec<PathBuf>,
    /// Branches created in ProposalWithBranch mode.
    pub branches_created: Vec<String>,
    /// Candidates skipped during execution, with reasons.
    pub skipped: Vec<(String, String)>,
}

impl PlanningResult {
    pub fn empty() -> Self {
        Self {
            plans: Vec::new(),
            skipped_candidates: Vec::new(),
        }
    }

    pub fn into_run_result(
        self,
        execution: crate::executor::ExecutionResult,
    ) -> ImprovementRunResult {
        ImprovementRunResult {
            plans_generated: self.plans.len(),
            skipped_candidates: self.skipped_candidates,
            proposals_written: execution.proposals_written,
            branches_created: execution.branches_created,
            skipped: execution.skipped,
        }
    }
}

impl ImprovementRunResult {
    pub fn empty() -> Self {
        PlanningResult::empty().into_run_result(crate::executor::ExecutionResult::empty())
    }
}

/// Generates fix plans from improvement candidates using an LLM.
pub struct ImprovementPlanner;

impl ImprovementPlanner {
    /// Generate fix plans for the given candidates.
    ///
    /// Each candidate is sent to the LLM independently. Candidates that fail
    /// planning are recorded and skipped so other candidates can still produce
    /// plans.
    pub async fn plan(
        candidates: &[ImprovementCandidate],
        provider: &dyn CompletionProvider,
        repo_root: &Path,
    ) -> PlanningResult {
        let mut result = PlanningResult::empty();
        result.plans.reserve(candidates.len());

        for candidate in candidates {
            match plan_single(candidate, provider, repo_root).await {
                Ok(plan) => result.plans.push(plan),
                Err(error) => {
                    record_skipped_candidate(&mut result.skipped_candidates, candidate, error)
                }
            }
        }

        result
    }
}

fn record_skipped_candidate(
    skipped_candidates: &mut Vec<SkippedCandidate>,
    candidate: &ImprovementCandidate,
    error: ImprovementError,
) {
    skipped_candidates.push(SkippedCandidate {
        name: candidate.finding.pattern_name.clone(),
        reason: summarize_planning_error(&error),
    });
}

fn summarize_planning_error(error: &ImprovementError) -> String {
    match error {
        ImprovementError::MissingPlanToolCall => "model did not produce a plan".to_string(),
        _ => error.to_string(),
    }
}

/// Plan a single candidate via LLM tool call.
async fn plan_single(
    candidate: &ImprovementCandidate,
    provider: &dyn CompletionProvider,
    repo_root: &Path,
) -> Result<FixPlan, ImprovementError> {
    let prompt = build_planning_prompt(candidate, repo_root);
    let request = CompletionRequest {
        model: String::new(),
        messages: vec![Message::user(prompt)],
        tools: vec![plan_tool_definition()],
        temperature: None,
        max_tokens: Some(4096),
        system_prompt: Some(PLANNER_SYSTEM_PROMPT.to_string()),
        thinking: None,
    };

    let response = provider.complete(request).await?;
    parse_plan_from_tool_calls(&response.tool_calls, candidate)
}

/// Build the user prompt describing the candidate for planning.
fn build_planning_prompt(candidate: &ImprovementCandidate, repo_root: &Path) -> String {
    let finding = &candidate.finding;
    let evidence_summary = finding
        .evidence
        .iter()
        .map(|evidence| {
            format!(
                "  - [{}] {}: {}",
                evidence.signal_kind, evidence.session_id, evidence.message
            )
        })
        .collect::<Vec<_>>()
        .join("\n");

    let suggested = finding
        .suggested_action
        .as_deref()
        .unwrap_or("(no suggestion)");

    format!(
        "Repository root: {repo}\n\n\
         Pattern: {name}\n\
         Description: {description}\n\
         Confidence: {confidence:?}\n\
         Evidence ({count} signals):\n{evidence}\n\n\
         Suggested action: {suggested}\n\n\
         Call the generate_fix_plan tool with a concrete plan.",
        repo = repo_root.display(),
        name = finding.pattern_name,
        description = finding.description,
        confidence = finding.confidence,
        count = finding.evidence.len(),
        evidence = evidence_summary,
    )
}

/// Tool definition for the LLM to call.
fn plan_tool_definition() -> ToolDefinition {
    ToolDefinition {
        name: PLAN_TOOL_NAME.to_string(),
        description: "Generate a fix plan for an improvement candidate.".to_string(),
        parameters: serde_json::json!({
            "type": "object",
            "additionalProperties": false,
            "required": ["target_files", "fix_description", "risk"],
            "properties": {
                "target_files": {
                    "type": "array",
                    "items": { "type": "string" },
                    "description": "File paths to modify"
                },
                "fix_description": {
                    "type": "string",
                    "description": "Natural language description of the fix"
                },
                "risk": {
                    "type": "string",
                    "enum": ["low", "medium", "high"],
                    "description": "Risk assessment"
                },
                "code_changes": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "additionalProperties": false,
                        "required": ["path", "description"],
                        "properties": {
                            "path": { "type": "string" },
                            "description": { "type": "string" },
                            "content": { "type": "string" }
                        }
                    },
                    "description": "Concrete file changes (optional)"
                }
            }
        }),
    }
}

/// Parsed tool call arguments.
#[derive(Debug, Deserialize)]
struct PlanToolArgs {
    target_files: Vec<String>,
    fix_description: String,
    risk: RiskLevel,
    code_changes: Option<Vec<FileChangeArgs>>,
}

#[derive(Debug, Deserialize)]
struct FileChangeArgs {
    path: String,
    description: String,
    content: Option<String>,
}

/// Parse the LLM tool call response into a `FixPlan`.
fn parse_plan_from_tool_calls(
    tool_calls: &[ToolCall],
    candidate: &ImprovementCandidate,
) -> Result<FixPlan, ImprovementError> {
    let call = tool_calls
        .iter()
        .find(|tool_call| tool_call.name == PLAN_TOOL_NAME)
        .ok_or(ImprovementError::MissingPlanToolCall)?;

    let args: PlanToolArgs = serde_json::from_value(call.arguments.clone())
        .map_err(|error| ImprovementError::Planning(format!("parse plan args: {error}")))?;

    let code_changes = args.code_changes.map(|changes| {
        changes
            .into_iter()
            .map(|change| FileChange {
                path: PathBuf::from(change.path),
                description: change.description,
                content: change.content,
            })
            .collect()
    });

    Ok(FixPlan {
        candidate: candidate.clone(),
        target_files: args.target_files.into_iter().map(PathBuf::from).collect(),
        fix_description: args.fix_description,
        code_changes,
        risk: args.risk,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use async_trait::async_trait;
    use fx_analysis::{AnalysisFinding, Confidence, SignalEvidence};
    use fx_core::signals::SignalKind;
    use fx_llm::{CompletionResponse, CompletionStream, ProviderCapabilities, ProviderError};
    use std::collections::VecDeque;
    use std::sync::Mutex;

    fn mk_candidate(name: &str) -> ImprovementCandidate {
        ImprovementCandidate {
            finding: AnalysisFinding {
                pattern_name: name.to_string(),
                description: "test description".to_string(),
                confidence: Confidence::High,
                evidence: vec![SignalEvidence {
                    session_id: "s1".to_string(),
                    signal_kind: SignalKind::Friction,
                    message: "timeout".to_string(),
                    timestamp_ms: 1,
                }],
                suggested_action: Some("fix it".to_string()),
            },
            fingerprint: format!("fp-{name}"),
        }
    }

    #[derive(Debug)]
    struct MockProvider {
        responses: Mutex<VecDeque<Result<CompletionResponse, ProviderError>>>,
    }

    impl MockProvider {
        fn new(responses: Vec<Result<CompletionResponse, ProviderError>>) -> Self {
            Self {
                responses: Mutex::new(VecDeque::from(responses)),
            }
        }
    }

    #[async_trait]
    impl CompletionProvider for MockProvider {
        async fn complete(
            &self,
            _req: CompletionRequest,
        ) -> Result<CompletionResponse, ProviderError> {
            self.responses
                .lock()
                .expect("mock provider lock")
                .pop_front()
                .expect("mock response")
        }

        async fn complete_stream(
            &self,
            _req: CompletionRequest,
        ) -> Result<CompletionStream, ProviderError> {
            Err(ProviderError::Provider("not supported".to_string()))
        }

        fn name(&self) -> &str {
            "mock"
        }

        fn supported_models(&self) -> Vec<String> {
            vec!["mock".to_string()]
        }

        fn capabilities(&self) -> ProviderCapabilities {
            ProviderCapabilities {
                supports_temperature: true,
                requires_streaming: false,
            }
        }
    }

    fn mock_with_tool_call(args: serde_json::Value) -> MockProvider {
        MockProvider::new(vec![Ok(tool_call_response(args))])
    }

    fn missing_tool_call_response() -> CompletionResponse {
        CompletionResponse {
            content: vec![],
            tool_calls: vec![],
            usage: None,
            stop_reason: Some("end_turn".to_string()),
        }
    }

    fn tool_call_response(args: serde_json::Value) -> CompletionResponse {
        CompletionResponse {
            content: vec![],
            tool_calls: vec![ToolCall {
                id: "call-1".to_string(),
                name: PLAN_TOOL_NAME.to_string(),
                arguments: args,
            }],
            usage: None,
            stop_reason: Some("tool_use".to_string()),
        }
    }

    fn skipped_candidate(reason: &str) -> SkippedCandidate {
        SkippedCandidate {
            name: "candidate".to_string(),
            reason: reason.to_string(),
        }
    }

    #[test]
    fn skipped_candidate_summary_uses_shared_reason() {
        let skipped = vec![
            skipped_candidate("model did not produce a plan"),
            skipped_candidate("model did not produce a plan"),
        ];

        assert_eq!(
            skipped_candidate_summary(&skipped),
            "2 candidates skipped (model did not produce a plan)"
        );
        assert_eq!(
            shared_skip_reason(&skipped),
            Some("model did not produce a plan")
        );
    }

    #[test]
    fn skipped_candidate_summary_reports_multiple_errors() {
        let skipped = vec![
            skipped_candidate("model did not produce a plan"),
            skipped_candidate("llm error: provider error: boom"),
        ];

        assert_eq!(
            skipped_candidate_summary(&skipped),
            "2 candidates skipped (multiple planning errors)"
        );
        assert_eq!(shared_skip_reason(&skipped), None);
    }

    #[tokio::test]
    async fn plan_with_no_candidates_returns_empty() {
        let provider = MockProvider::new(Vec::new());

        let result = ImprovementPlanner::plan(&[], &provider, Path::new("/repo")).await;
        assert!(result.plans.is_empty());
        assert!(result.skipped_candidates.is_empty());
    }

    #[tokio::test]
    async fn plan_generates_fix_plan_from_tool_call() {
        let provider = mock_with_tool_call(serde_json::json!({
            "target_files": ["src/main.rs"],
            "fix_description": "Increase timeout to 30s",
            "risk": "low",
            "code_changes": [{
                "path": "src/main.rs",
                "description": "change timeout constant",
                "content": "const TIMEOUT_MS: u64 = 30000;"
            }]
        }));

        let candidates = vec![mk_candidate("timeout-loop")];
        let result = ImprovementPlanner::plan(&candidates, &provider, Path::new("/repo")).await;

        assert_eq!(result.plans.len(), 1);
        assert!(result.skipped_candidates.is_empty());
        assert_eq!(result.plans[0].fix_description, "Increase timeout to 30s");
        assert_eq!(result.plans[0].risk, RiskLevel::Low);
        assert_eq!(
            result.plans[0].target_files,
            vec![PathBuf::from("src/main.rs")]
        );

        let changes = result.plans[0].code_changes.as_ref().expect("code changes");
        assert_eq!(changes.len(), 1);
        assert_eq!(
            changes[0].content.as_deref(),
            Some("const TIMEOUT_MS: u64 = 30000;")
        );
    }

    #[tokio::test]
    async fn plan_without_code_changes() {
        let provider = mock_with_tool_call(serde_json::json!({
            "target_files": ["src/config.rs"],
            "fix_description": "Refactor config",
            "risk": "medium"
        }));

        let candidates = vec![mk_candidate("config-issue")];
        let result = ImprovementPlanner::plan(&candidates, &provider, Path::new("/repo")).await;

        assert_eq!(result.plans.len(), 1);
        assert!(result.plans[0].code_changes.is_none());
        assert_eq!(result.plans[0].risk, RiskLevel::Medium);
        assert!(result.skipped_candidates.is_empty());
    }

    #[tokio::test]
    async fn plan_skips_candidate_on_llm_error() {
        let provider = MockProvider::new(vec![Err(ProviderError::Provider("boom".to_string()))]);
        let candidates = vec![mk_candidate("error-case")];

        let result = ImprovementPlanner::plan(&candidates, &provider, Path::new("/repo")).await;

        assert!(result.plans.is_empty());
        assert_eq!(result.skipped_candidates.len(), 1);
        assert_eq!(result.skipped_candidates[0].name, "error-case");
        assert_eq!(
            result.skipped_candidates[0].reason,
            "llm error: provider error: boom"
        );
    }

    #[tokio::test]
    async fn plan_skips_candidate_when_tool_call_missing() {
        let provider = MockProvider::new(vec![Ok(missing_tool_call_response())]);
        let candidates = vec![mk_candidate("missing-tool-call")];

        let result = ImprovementPlanner::plan(&candidates, &provider, Path::new("/repo")).await;

        assert!(result.plans.is_empty());
        assert_eq!(result.skipped_candidates.len(), 1);
        assert_eq!(result.skipped_candidates[0].name, "missing-tool-call");
        assert_eq!(
            result.skipped_candidates[0].reason,
            "model did not produce a plan"
        );
    }

    #[tokio::test]
    async fn plan_keeps_successful_candidates_when_another_fails() {
        let provider = MockProvider::new(vec![
            Ok(missing_tool_call_response()),
            Ok(tool_call_response(serde_json::json!({
                "target_files": ["src/lib.rs"],
                "fix_description": "General fix",
                "risk": "high"
            }))),
        ]);
        let candidates = vec![mk_candidate("failed"), mk_candidate("succeeds")];

        let result = ImprovementPlanner::plan(&candidates, &provider, Path::new("/repo")).await;

        assert_eq!(result.plans.len(), 1);
        assert_eq!(result.plans[0].candidate.finding.pattern_name, "succeeds");
        assert_eq!(result.plans[0].risk, RiskLevel::High);
        assert_eq!(result.skipped_candidates.len(), 1);
        assert_eq!(result.skipped_candidates[0].name, "failed");
    }

    #[tokio::test]
    async fn plan_multiple_candidates() {
        let provider = MockProvider::new(vec![
            Ok(tool_call_response(serde_json::json!({
                "target_files": ["src/lib.rs"],
                "fix_description": "General fix",
                "risk": "high"
            }))),
            Ok(tool_call_response(serde_json::json!({
                "target_files": ["src/lib.rs"],
                "fix_description": "General fix",
                "risk": "high"
            }))),
        ]);

        let candidates = vec![mk_candidate("a"), mk_candidate("b")];
        let result = ImprovementPlanner::plan(&candidates, &provider, Path::new("/repo")).await;

        assert_eq!(result.plans.len(), 2);
        assert_eq!(result.plans[0].risk, RiskLevel::High);
        assert_eq!(result.plans[0].candidate.finding.pattern_name, "a");
        assert_eq!(result.plans[1].candidate.finding.pattern_name, "b");
        assert!(result.skipped_candidates.is_empty());
    }
}
