//! Act-step execution result types.

use crate::cancellation::CancellationToken;
use crate::decide::Decision;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};

/// Token accounting for loop steps that call an LLM.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct TokenUsage {
    /// Estimated input tokens consumed by prompts/context.
    pub input_tokens: u64,
    /// Estimated output tokens generated by the model.
    pub output_tokens: u64,
}

impl TokenUsage {
    /// Total estimated token count.
    pub fn total_tokens(self) -> u64 {
        self.input_tokens.saturating_add(self.output_tokens)
    }

    /// Add another usage sample.
    pub fn accumulate(&mut self, other: TokenUsage) {
        self.input_tokens = self.input_tokens.saturating_add(other.input_tokens);
        self.output_tokens = self.output_tokens.saturating_add(other.output_tokens);
    }
}

/// Tool execution failure.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolExecutorError {
    /// Human-readable error description.
    pub message: String,
    /// Whether retrying might succeed.
    pub recoverable: bool,
}

/// Tool execution result.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolResult {
    /// Tool call identifier generated by the LLM.
    pub tool_call_id: String,
    /// Name of the tool that was requested.
    pub tool_name: String,
    /// Whether the tool succeeded.
    pub success: bool,
    /// Human-readable tool output.
    pub output: String,
}

/// Tool execution abstraction for kernel act step.
#[async_trait]
pub trait ToolExecutor: Send + Sync + std::fmt::Debug {
    /// Execute requested tool calls and return tool results.
    ///
    /// When `cancel` is `Some`, implementations should check
    /// [`CancellationToken::is_cancelled`] between individual tool calls
    /// and return early (with partial results) if cancellation is observed.
    async fn execute_tools(
        &self,
        calls: &[fx_llm::ToolCall],
        cancel: Option<&CancellationToken>,
    ) -> Result<Vec<ToolResult>, ToolExecutorError>;

    /// Tool definitions exposed to the reasoning model.
    fn tool_definitions(&self) -> Vec<fx_llm::ToolDefinition> {
        Vec::new()
    }
}

/// Result of the Act step.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ActionResult {
    /// Decision selected by the Decide step.
    pub decision: Decision,
    /// Outputs from executed tools.
    pub tool_results: Vec<ToolResult>,
    /// User-visible text response.
    pub response_text: String,
    /// Tokens consumed while producing this action output.
    pub tokens_used: TokenUsage,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn token_usage_accumulates_and_totals() {
        let mut usage = TokenUsage {
            input_tokens: 10,
            output_tokens: 20,
        };

        usage.accumulate(TokenUsage {
            input_tokens: 7,
            output_tokens: 3,
        });

        assert_eq!(usage.input_tokens, 17);
        assert_eq!(usage.output_tokens, 23);
        assert_eq!(usage.total_tokens(), 40);
    }
}
