//! Act-step execution result types.

use crate::cancellation::CancellationToken;
use crate::decide::Decision;
use async_trait::async_trait;
use serde::{Deserialize, Serialize};
use std::num::NonZeroUsize;

/// Token accounting for loop steps that call an LLM.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct TokenUsage {
    /// Estimated input tokens consumed by prompts/context.
    pub input_tokens: u64,
    /// Estimated output tokens generated by the model.
    pub output_tokens: u64,
}

impl TokenUsage {
    /// Total estimated token count.
    pub fn total_tokens(self) -> u64 {
        self.input_tokens.saturating_add(self.output_tokens)
    }

    /// Add another usage sample.
    pub fn accumulate(&mut self, other: TokenUsage) {
        self.input_tokens = self.input_tokens.saturating_add(other.input_tokens);
        self.output_tokens = self.output_tokens.saturating_add(other.output_tokens);
    }
}

/// Tool execution failure.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolExecutorError {
    /// Human-readable error description.
    pub message: String,
    /// Whether retrying might succeed.
    pub recoverable: bool,
}

/// Controls parallel execution of tool calls.
#[derive(Debug, Clone, Default)]
pub struct ConcurrencyPolicy {
    /// Maximum number of tool calls to execute in parallel.
    /// `None` means unlimited (all calls run concurrently).
    pub max_parallel: Option<NonZeroUsize>,
    /// Per-tool-call timeout. If a call exceeds this, it returns
    /// an error result (not a panic).
    pub timeout_per_call: Option<std::time::Duration>,
}

/// Declares whether a tool's results may be cached for identical inputs.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum ToolCacheability {
    /// Results are deterministic and safe to cache within a cycle.
    Cacheable,
    /// Results should never be cached unless explicitly opted in.
    NeverCache,
    /// Tool has side effects and may invalidate cache entries.
    SideEffect,
}

/// Cache counters exposed by caching-capable executors.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq, Default)]
pub struct ToolCacheStats {
    pub hits: u64,
    pub misses: u64,
    pub entries: u64,
    pub evictions: u64,
}

/// Tool execution result.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
pub struct ToolResult {
    /// Tool call identifier generated by the LLM.
    pub tool_call_id: String,
    /// Name of the tool that was requested.
    pub tool_name: String,
    /// Whether the tool succeeded.
    pub success: bool,
    /// Human-readable tool output.
    pub output: String,
}

/// Returns true when the optional cancellation token has been cancelled.
#[must_use]
pub fn is_cancelled(cancel: Option<&CancellationToken>) -> bool {
    cancel.is_some_and(CancellationToken::is_cancelled)
}

/// Standardized tool result for cancellation.
#[must_use]
pub fn cancelled_result(tool_call_id: &str, tool_name: &str) -> ToolResult {
    ToolResult {
        tool_call_id: tool_call_id.to_string(),
        tool_name: tool_name.to_string(),
        success: false,
        output: "tool execution cancelled".to_string(),
    }
}

/// Standardized tool result for per-call timeout.
#[must_use]
pub fn timed_out_result(tool_call_id: &str, tool_name: &str) -> ToolResult {
    ToolResult {
        tool_call_id: tool_call_id.to_string(),
        tool_name: tool_name.to_string(),
        success: false,
        output: "tool execution timed out".to_string(),
    }
}

/// Tool execution abstraction for kernel act step.
#[async_trait]
pub trait ToolExecutor: Send + Sync + std::fmt::Debug {
    /// Execute requested tool calls and return tool results.
    ///
    /// When `cancel` is `Some`, implementations should check
    /// [`CancellationToken::is_cancelled`] between individual tool calls.
    /// The returned vector should preserve call-to-result alignment: each
    /// requested call must produce one result, using a cancelled result if
    /// cancellation is observed before execution begins.
    async fn execute_tools(
        &self,
        calls: &[fx_llm::ToolCall],
        cancel: Option<&CancellationToken>,
    ) -> Result<Vec<ToolResult>, ToolExecutorError>;

    /// Returns the concurrency policy for parallel tool execution.
    /// Default: unlimited parallelism, no per-call timeout.
    fn concurrency_policy(&self) -> ConcurrencyPolicy {
        ConcurrencyPolicy::default()
    }

    /// Tool definitions exposed to the reasoning model.
    fn tool_definitions(&self) -> Vec<fx_llm::ToolDefinition> {
        Vec::new()
    }

    /// Classifies whether a tool may be cached for identical inputs.
    fn cacheability(&self, tool_name: &str) -> ToolCacheability {
        let _ = tool_name;
        ToolCacheability::NeverCache
    }

    /// Clears any tool-result cache state for the current cycle.
    fn clear_cache(&self) {}

    /// Returns cache statistics when supported by the executor.
    fn cache_stats(&self) -> Option<ToolCacheStats> {
        None
    }
}

/// Result of the Act step.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
pub struct ActionResult {
    /// Decision selected by the Decide step.
    pub decision: Decision,
    /// Outputs from executed tools.
    pub tool_results: Vec<ToolResult>,
    /// User-visible text response.
    pub response_text: String,
    /// Tokens consumed while producing this action output.
    pub tokens_used: TokenUsage,
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn concurrency_policy_default_is_unlimited() {
        let policy = ConcurrencyPolicy::default();
        assert_eq!(policy.max_parallel, None);
        assert!(policy.timeout_per_call.is_none());
    }

    #[test]
    fn concurrency_policy_custom_values() {
        let policy = ConcurrencyPolicy {
            max_parallel: Some(NonZeroUsize::new(4).expect("non-zero")),
            timeout_per_call: Some(std::time::Duration::from_secs(30)),
        };
        assert_eq!(policy.max_parallel.map(NonZeroUsize::get), Some(4));
        assert_eq!(policy.timeout_per_call.unwrap().as_secs(), 30);
    }

    #[test]
    fn token_usage_accumulates_and_totals() {
        let mut usage = TokenUsage {
            input_tokens: 10,
            output_tokens: 20,
        };

        usage.accumulate(TokenUsage {
            input_tokens: 7,
            output_tokens: 3,
        });

        assert_eq!(usage.input_tokens, 17);
        assert_eq!(usage.output_tokens, 23);
        assert_eq!(usage.total_tokens(), 40);
    }
}
